import {
    createElement,
    EllipsisVertical,
    Check,
    VolumeOff,
    Volume1,
    Volume2,
    Play,
    Pause,
    Plus,
    Minus,
    RotateCcw,
    Download,
    ShieldCheck,
    RefreshCw,
    SunMoon,
    Moon,
    Sun,
    Scissors,
    Copy,
    ClipboardPaste,
    Delete,
    ArrowBigUp,
    Grid2X2,
    CornerDownLeft,
    TextCursor,
    Undo2,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    Redo2,
} from 'lucide';
const icons = {
    more: EllipsisVertical,
    check: Check,
    mute: VolumeOff,
    quieter: Volume1,
    louder: Volume2,
    play: Play,
    pause: Pause,
    plus: Plus,
    minus: Minus,
    reset: RotateCcw,
    install: Download,
    trust: ShieldCheck,
    reload: RefreshCw,
    auto: SunMoon,
    dark: Moon,
    light: Sun,
    up: ArrowUp,
    down: ArrowDown,
    left: ArrowLeft,
    right: ArrowRight,
    undo: Undo2,
    redo: Redo2,
    cut: Scissors,
    copy: Copy,
    paste: ClipboardPaste,
    delete: Delete,
    shift: ArrowBigUp,
    windows: Grid2X2,
    enter: CornerDownLeft,
    text: TextCursor,
};
// Sized in CSS (rem), not with width/height attributes in pixels, so icons follow the interface scale.
export function icon(name) {
    return createElement(icons[name], {
        class: name === 'more' ? 'icon icon-large' : 'icon',
        'stroke-width': 1.5,
        'aria-hidden': 'true',
        focusable: 'false',
    });
}
export function addIcons(root) {
    root.querySelectorAll('[data-icon]').forEach((element) => element.replaceChildren(icon(element.dataset.icon)));
}
